# yaml-language-server: $schema=https://promptfoo.dev/config-schema.json

# Learn more about building a configuration: https://promptfoo.dev/docs/configuration/guide

description: 'My eval'

prompts:
  - 'List the available MCP servers and resources you have available to you'

providers:
  - id: azure:chat:gpt-5-mini
    config:
      reasoning:
        effort: 'medium'
      max_completion_tokens: 25000
      isReasoningModel: true
      mcp:
        enabled: true
        servers:
          - command: npx
            args:
              - '@fluentui-contrib/token-analyzer-mcp'
            name: test-token-mcp

defaultTest:
  options:
    provider:
      id: azure:chat:gpt-5-mini
      config:
        isReasoningModel: true
        reasoning:
          effort: 'medium'
        max_completion_tokens: 25000

tests:
  - vars:
      resource: Token Structure Documentation

    assert:
      - type: llm-rubric
        value: Ensure the output shows this MCP resource is about the structure of tokens within the Fluent UI design system. It should not include errors or queries about how to get MCP resources. If it does, this should fail.
